name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: jsbt v0.5.1
    uses: paulmillr/jsbt/.github/workflows/release.yml@231cc389fe2f825b6531285ad8c275584bf76588
    permissions:
      contents: read
      id-token: write
