name: Run scheduled tests
on:
  schedule:
    - cron: '0 20 * * 1,4' # 14:00 bi-weekly (mon, thu)
  workflow_dispatch:
jobs:
  slow:
    name: Large multisig tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@d156c5951d47d615d673d039aa03de6b9669449f
    with:
      npm-task: test:slow
