name: Large tests
on:
  schedule:
    - cron: '0 20 * * 1,4' # 14:00 bi-weekly (mon, thu)
  workflow_dispatch:
jobs:
  slow:
    name: Large multisig tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@c138efca67d90dce86a7cc22c01d6b66d193ea7a
    with:
      npm-task: test:slow
